//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 03:04:21 PM IST 
//


package com.tayyarah.api.hotel.rezlive.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rezlive.hotel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rezlive.hotel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BookingResponse }
     * 
     */
    public BookingResponse createBookingResponse() {
        return new BookingResponse();
    }

    /**
     * Create an instance of {@link BookingResponse.BookingRequest }
     * 
     */
    public BookingResponse.BookingRequest createBookingResponseBookingRequest() {
        return new BookingResponse.BookingRequest();
    }

    /**
     * Create an instance of {@link BookingResponse.BookingRequest.Booking }
     * 
     */
    public BookingResponse.BookingRequest.Booking createBookingResponseBookingRequestBooking() {
        return new BookingResponse.BookingRequest.Booking();
    }

    /**
     * Create an instance of {@link BookingResponse.BookingRequest.Booking.RoomDetails }
     * 
     */
    public BookingResponse.BookingRequest.Booking.RoomDetails createBookingResponseBookingRequestBookingRoomDetails() {
        return new BookingResponse.BookingRequest.Booking.RoomDetails();
    }

    /**
     * Create an instance of {@link BookingResponse.BookingRequest.Booking.RoomDetails.RoomDetail }
     * 
     */
    public BookingResponse.BookingRequest.Booking.RoomDetails.RoomDetail createBookingResponseBookingRequestBookingRoomDetailsRoomDetail() {
        return new BookingResponse.BookingRequest.Booking.RoomDetails.RoomDetail();
    }

    /**
     * Create an instance of {@link BookingResponse.BookingRequest.Booking.RoomDetails.RoomDetail.Guests }
     * 
     */
    public BookingResponse.BookingRequest.Booking.RoomDetails.RoomDetail.Guests createBookingResponseBookingRequestBookingRoomDetailsRoomDetailGuests() {
        return new BookingResponse.BookingRequest.Booking.RoomDetails.RoomDetail.Guests();
    }

    /**
     * Create an instance of {@link BookingResponse.BookingDetails }
     * 
     */
    public BookingResponse.BookingDetails createBookingResponseBookingDetails() {
        return new BookingResponse.BookingDetails();
    }

    /**
     * Create an instance of {@link BookingResponse.BookingRequest.Authentication }
     * 
     */
    public BookingResponse.BookingRequest.Authentication createBookingResponseBookingRequestAuthentication() {
        return new BookingResponse.BookingRequest.Authentication();
    }

    /**
     * Create an instance of {@link BookingResponse.BookingRequest.Booking.RoomDetails.RoomDetail.Guests.Guest }
     * 
     */
    public BookingResponse.BookingRequest.Booking.RoomDetails.RoomDetail.Guests.Guest createBookingResponseBookingRequestBookingRoomDetailsRoomDetailGuestsGuest() {
        return new BookingResponse.BookingRequest.Booking.RoomDetails.RoomDetail.Guests.Guest();
    }

}
