//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.19 at 02:56:27 PM IST 
//


package com.tayyarah.api.hotel.rezlive.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CancellationInformations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CancellationInformation" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Info" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cancellationInformations"
})
@XmlRootElement(name = "CancellationPolicyResponse")
public class CancellationPolicyResponse
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "CancellationInformations", required = true)
    protected CancellationPolicyResponse.CancellationInformations cancellationInformations;

    /**
     * Gets the value of the cancellationInformations property.
     * 
     * @return
     *     possible object is
     *     {@link CancellationPolicyResponse.CancellationInformations }
     *     
     */
    public CancellationPolicyResponse.CancellationInformations getCancellationInformations() {
        return cancellationInformations;
    }

    /**
     * Sets the value of the cancellationInformations property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancellationPolicyResponse.CancellationInformations }
     *     
     */
    public void setCancellationInformations(CancellationPolicyResponse.CancellationInformations value) {
        this.cancellationInformations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CancellationInformation" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Info" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cancellationInformations",
        "info"
    })
    public static class CancellationInformations
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(name = "CancellationInformation", required = true)
        protected List<CancellationPolicyResponse.CancellationInformations.CancellationInformation> cancellationInformations;
        @XmlElement(name = "Info", required = true)
        protected String info;

        /**
         * Gets the value of the cancellationInformations property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cancellationInformations property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCancellationInformations().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CancellationPolicyResponse.CancellationInformations.CancellationInformation }
         * 
         * 
         */
        public List<CancellationPolicyResponse.CancellationInformations.CancellationInformation> getCancellationInformations() {
            if (cancellationInformations == null) {
                cancellationInformations = new ArrayList<CancellationPolicyResponse.CancellationInformations.CancellationInformation>();
            }
            return this.cancellationInformations;
        }

        /**
         * Gets the value of the info property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInfo() {
            return info;
        }

        /**
         * Sets the value of the info property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInfo(String value) {
            this.info = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "startDate",
            "endDate",
            "chargeType",
            "chargeAmount",
            "currency"
        })
        public static class CancellationInformation
            implements Serializable
        {

            private final static long serialVersionUID = -1L;
            @XmlElement(name = "StartDate", required = true)
            protected String startDate;
            @XmlElement(name = "EndDate", required = true)
            protected String endDate;
            @XmlElement(name = "ChargeType", required = true)
            protected String chargeType;
            @XmlElement(name = "ChargeAmount", required = true)
            protected BigDecimal chargeAmount;
            @XmlElement(name = "Currency", required = true)
            protected String currency;

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartDate(String value) {
                this.startDate = value;
            }

            /**
             * Gets the value of the endDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndDate() {
                return endDate;
            }

            /**
             * Sets the value of the endDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndDate(String value) {
                this.endDate = value;
            }

            /**
             * Gets the value of the chargeType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChargeType() {
                return chargeType;
            }

            /**
             * Sets the value of the chargeType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargeType(String value) {
                this.chargeType = value;
            }

            /**
             * Gets the value of the chargeAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getChargeAmount() {
                return chargeAmount;
            }

            /**
             * Sets the value of the chargeAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setChargeAmount(BigDecimal value) {
                this.chargeAmount = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

        }

    }

}
