//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.24 at 11:34:13 AM IST 
//


package com.tayyarah.api.hotel.reznext.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * <p>Java class for RoomTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoomTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoomDescription" type="{}RoomDescriptionType"/>
 *         &lt;element name="RoomAmenities" type="{}RoomAmenitiesType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RoomTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MaxPersons" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MaxChildAge" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MinChildAge" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoomTypeType", propOrder = {
    "roomDescription",
    "roomAmenities"
})
public class RoomTypeType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "RoomDescription", required = true)
    protected RoomDescriptionType roomDescription;
    @XmlElement(name = "RoomAmenities", required = true)
    protected RoomAmenitiesType roomAmenities;
    @XmlAttribute(name = "RoomTypeCode")
    protected String roomTypeCode;
    @JsonIgnore
    @XmlAttribute(name = "MaxPersons")
    protected int maxPersons;
    
    @XmlAttribute(name = "MaxChildAge")
    protected int maxChildAge;
    @XmlAttribute(name = "MinChildAge")
    protected int minChildAge;

    /**
     * Gets the value of the roomDescription property.
     * 
     * @return
     *     possible object is
     *     {@link RoomDescriptionType }
     *     
     */
    public RoomDescriptionType getRoomDescription() {
        return roomDescription;
    }

    /**
     * Sets the value of the roomDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomDescriptionType }
     *     
     */
    public void setRoomDescription(RoomDescriptionType value) {
        this.roomDescription = value;
    }

    /**
     * Gets the value of the roomAmenities property.
     * 
     * @return
     *     possible object is
     *     {@link RoomAmenitiesType }
     *     
     */
    public RoomAmenitiesType getRoomAmenities() {
        return roomAmenities;
    }

    /**
     * Sets the value of the roomAmenities property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomAmenitiesType }
     *     
     */
    public void setRoomAmenities(RoomAmenitiesType value) {
        this.roomAmenities = value;
    }

    /**
     * Gets the value of the roomTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomTypeCode() {
        return roomTypeCode;
    }

    /**
     * Sets the value of the roomTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomTypeCode(String value) {
        this.roomTypeCode = value;
    }

    /**
     * Gets the value of the maxPersons property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public int getMaxPersons() {
        return maxPersons;
    }

    /**
     * Sets the value of the maxPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMaxPersons(Byte value) {
        this.maxPersons = value;
    }

    /**
     * Gets the value of the maxChildAge property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public int getMaxChildAge() {
        return maxChildAge;
    }

    /**
     * Sets the value of the maxChildAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMaxChildAge(Byte value) {
        this.maxChildAge = value;
    }

    /**
     * Gets the value of the minChildAge property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public int getMinChildAge() {
        return minChildAge;
    }

    public void setMaxPersons(int maxPersons) {
		this.maxPersons = maxPersons;
	}

	public void setMaxChildAge(int maxChildAge) {
		this.maxChildAge = maxChildAge;
	}

	public void setMinChildAge(int minChildAge) {
		this.minChildAge = minChildAge;
	}

	/**
     * Sets the value of the minChildAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMinChildAge(Byte value) {
        this.minChildAge = value;
    }

}
