//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.24 at 11:34:13 AM IST 
//


package com.tayyarah.api.hotel.reznext.model;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;





/**
 * <p>Java class for BasicPropertyInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicPropertyInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Position" type="{}PositionType"/>
 *         &lt;element name="Address" type="{}AddressType"/>
 *         &lt;element name="AwardRating" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="HotelImages" type="{}HotelImagesType"/>
 *         &lt;element name="HotelFeatures" type="{}HotelFeaturesType"/>
 *         &lt;element name="TaxSummary" type="{}TaxSummaryType"/>
 *         &lt;element name="ContactNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RezNextContactNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HotelDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HotelPolicy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CheckIn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CheckOut" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="HotelCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HotelName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicPropertyInfoType", propOrder = {
    "position",
    "address",
    "award",
    "awardRating",
    "hotelImages",
    "hotelFeatures",
    "taxSummary",
    "contactNumber",
    "rezNextContactNumber",
    "hotelDescription",
    "currency",
    "hotelPolicy",
    "checkIn",
    "checkOut",
    "baseRate",
    "value"
})
public class BasicPropertyInfoType
    implements Serializable
{

    public BigDecimal getBaseRate() {
		return baseRate;
	}

	public void setBaseRate(BigDecimal baseRate) {
		this.baseRate = baseRate;
	}

	private final static long serialVersionUID = -1L;
    @XmlElement(name = "Position", required = true)
    protected PositionType position;
    @XmlElement(name = "Address", required = true)
    protected AddressType address;
    @XmlElement(name = "Award", required = true)
    protected AwardType award;
    @XmlElement(name = "AwardRating")
    protected int awardRating;
    @XmlElement(name = "HotelImages", required = true)
    protected HotelImagesType hotelImages;
    @XmlElement(name = "HotelFeatures", required = true)
    protected HotelFeaturesType hotelFeatures;
    @XmlElement(name = "TaxSummary", required = true)
    protected TaxSummaryType taxSummary;
    @XmlElement(name = "ContactNumber", required = true)
    protected String contactNumber;
    @XmlElement(name = "RezNextContactNumber")
    protected String rezNextContactNumber;
    @XmlElement(name = "HotelDescription", required = true)
    protected String hotelDescription;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "HotelPolicy", required = true)
    protected String hotelPolicy;
    @XmlElement(name = "CheckIn")
    protected String checkIn;
    @XmlElement(name = "CheckOut")
    protected String checkOut;
    @XmlAttribute(name = "HotelCode")
    protected String hotelCode;
    
   

	@XmlElement(name = "BaseRate")
    protected BigDecimal baseRate;
    @XmlAttribute(name = "HotelName")
    protected String hotelName;
    @XmlAttribute(name="Value")
    protected String value;
   

    public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	/**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link PositionType }
     *     
     */
    public PositionType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionType }
     *     
     */
    public void setPosition(PositionType value) {
        this.position = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the awardRating property.
     * 
     */
    public int getAwardRating() {
        return awardRating;
    }

    /**
     * Sets the value of the awardRating property.
     * 
     */
    public void setAwardRating(int value) {
        this.awardRating = value;
    }

    /**
     * Gets the value of the hotelImages property.
     * 
     * @return
     *     possible object is
     *     {@link HotelImagesType }
     *     
     */
    public HotelImagesType getHotelImages() {
        return hotelImages;
    }

    /**
     * Sets the value of the hotelImages property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelImagesType }
     *     
     */
    public void setHotelImages(HotelImagesType value) {
        this.hotelImages = value;
    }

    /**
     * Gets the value of the hotelFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link HotelFeaturesType }
     *     
     */
    public HotelFeaturesType getHotelFeatures() {
        return hotelFeatures;
    }

    /**
     * Sets the value of the hotelFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelFeaturesType }
     *     
     */
    public void setHotelFeatures(HotelFeaturesType value) {
        this.hotelFeatures = value;
    }

    /**
     * Gets the value of the taxSummary property.
     * 
     * @return
     *     possible object is
     *     {@link TaxSummaryType }
     *     
     */
    public TaxSummaryType getTaxSummary() {
        return taxSummary;
    }

    /**
     * Sets the value of the taxSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxSummaryType }
     *     
     */
    public void setTaxSummary(TaxSummaryType value) {
        this.taxSummary = value;
    }

    /**
     * Gets the value of the contactNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * Sets the value of the contactNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactNumber(String value) {
        this.contactNumber = value;
    }

    /**
     * Gets the value of the rezNextContactNumber property.
     * 
     */
    public String getRezNextContactNumber() {
        return rezNextContactNumber;
    }

    /**
     * Sets the value of the rezNextContactNumber property.
     * 
     */
    public void setRezNextContactNumber(String value) {
        this.rezNextContactNumber = value;
    }

    /**
     * Gets the value of the hotelDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelDescription() {
        return hotelDescription;
    }

    /**
     * Sets the value of the hotelDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelDescription(String value) {
        this.hotelDescription = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the hotelPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelPolicy() {
        return hotelPolicy;
    }

    /**
     * Sets the value of the hotelPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelPolicy(String value) {
        this.hotelPolicy = value;
    }

    /**
     * Gets the value of the checkIn property.
     * 
     */
    public String getCheckIn() {
        return checkIn;
    }

    /**
     * Sets the value of the checkIn property.
     * 
     */
    public void setCheckIn(String value) {
        this.checkIn = value;
    }

    /**
     * Gets the value of the checkOut property.
     * 
     */
    public String getCheckOut() {
        return checkOut;
    }

    /**
     * Sets the value of the checkOut property.
     * 
     */
    public void setCheckOut(String value) {
        this.checkOut = value;
    }

    /**
     * Gets the value of the hotelCode property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * Sets the value of the hotelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setHotelCode(String value) {
        this.hotelCode = value;
    }

    /**
     * Gets the value of the hotelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * Sets the value of the hotelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelName(String value) {
        this.hotelName = value;
    }

    /**
     * Gets the value of the award property.
     * 
     * @return
     *     possible object is
     *     {@link AwardType }
     *     
     */
    public AwardType getAward() {
        return award;
    }

    /**
     * Sets the value of the award property.
     * 
     * @param value
     *     allowed object is
     *     {@link AwardType }
     *     
     */
    public void setAward(AwardType value) {
        this.award = value;
    }


}
