//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.08.09 at 04:51:51 PM IST
//


package com.tayyarah.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.tayyarah.common.gstconfig.model.HotelGstTax;
import com.tayyarah.common.servicetaxconfig.model.HotelServiceTax;



/**
 * <p>Java class for TotalType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TotalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Taxes" type="{http://www.opentravel.org/OTA/2003/05}TaxesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AdditionalFeesExcludedIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AmountAfterTax" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="AmountBeforeTax" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="AmountIncludingMarkup" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RateOverrideIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ServiceOverrideIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="editCommission" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="editNetRate" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="editSellRate" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="editServiceCharge" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="editServiceTax" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="editTotalTax" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DecimalPlaces" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TotalType", propOrder = {
		"taxes"
})
@XmlSeeAlso({
	DiscountType.class,
	com.tayyarah.hotel.model.RateUploadType.BaseByGuestAmts.BaseByGuestAmt.class
})
public class TotalType
implements Serializable, Cloneable
{


	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	private final static long serialVersionUID = -1L;
	@XmlElement(name = "Taxes")
	protected TaxesType taxes;
	@XmlAttribute(name = "AdditionalFeesExcludedIndicator")
	protected Boolean additionalFeesExcludedIndicator;

	@XmlAttribute(name = "AmountAfterTax")
	protected BigDecimal amountAfterTax;
	@XmlAttribute(name = "AmountBeforeTax")
	protected BigDecimal amountBeforeTax;
	@XmlAttribute(name = "AmountIncludingMarkup")
	protected BigDecimal amountIncludingMarkup;

	@XmlAttribute(name = "RateOverrideIndicator")
	protected Boolean rateOverrideIndicator;
	@XmlAttribute(name = "ServiceOverrideIndicator")
	protected Boolean serviceOverrideIndicator;
	@XmlAttribute(name = "Type")
	protected String type;
	@XmlAttribute(name = "editCommission")
	protected BigDecimal editCommission;
	@XmlAttribute(name = "editNetRate")
	protected BigDecimal editNetRate;
	@XmlAttribute(name = "editSellRate")
	protected BigDecimal editSellRate;
	@XmlAttribute(name = "editServiceCharge")
	protected BigDecimal editServiceCharge;
	@XmlAttribute(name = "editServiceTax")
	protected BigDecimal editServiceTax;
	@XmlAttribute(name = "editTotalTax")
	protected BigDecimal editTotalTax;
	@XmlAttribute(name = "CurrencyCode")
	protected String currencyCode;
	@XmlAttribute(name = "DecimalPlaces")
	protected BigInteger decimalPlaces;

	@XmlAttribute(name = "TotalAmountPayable")
	protected BigDecimal totalAmountPayable;// total payable

	@XmlElement(name = "Discount")
	protected List<AmountType.Discount> discounts;

	@XmlAttribute(name = "TotalRoomPrice")
	protected BigDecimal totalRoomPrice;//RoomPrice

	@JsonProperty("TotalExtraGuestCharge")
	private BigDecimal totalExtraGuestCharge;

	@JsonProperty("TotalChildCharge")
	private BigDecimal totalChildCharge;

	@JsonProperty("TotalOtherCharges")
	private BigDecimal totalOtherCharges;

	@JsonProperty("TotalOfferedPrice")
	private BigDecimal totalOfferedPrice;

	@JsonProperty("ApiPublishedPriceTotal")
	private BigDecimal apiPublishedPriceTotal;

	@JsonProperty("TotalAgentCommission")
	private BigDecimal totalAgentCommission;

	@JsonProperty("TotalAgentMarkUp")
	private BigDecimal totalAgentMarkUp;

	@JsonProperty("TotalServiceTax")
	private BigDecimal totalServiceTax;

	@JsonProperty("TotalTDS")
	private BigDecimal totalTDS;

	@JsonProperty("TotalTax")
	private BigDecimal totalTax;

	@JsonProperty("TotalDiscount")
	private BigDecimal totalDiscount;

	@XmlAttribute(name = "HotelServiceTax")
	protected HotelServiceTax hotelServiceTax;
	
	@JsonProperty("PayableAmount")
	protected BigDecimal payableAmount; // total payable
	
	@XmlAttribute(name = "HotelGstTax")
	protected HotelGstTax hotelGstTax;

	public HotelGstTax getHotelGstTax() {
		return hotelGstTax;
	}

	public void setHotelGstTax(HotelGstTax hotelGstTax) {
		this.hotelGstTax = hotelGstTax;
	}

	public BigDecimal getPayableAmount() {
		return payableAmount;
	}

	public void setPayableAmount(BigDecimal payableAmount) {
		this.payableAmount = payableAmount;
	}

	public HotelServiceTax getHotelServiceTax() {
		return hotelServiceTax;
	}

	public void setHotelServiceTax(HotelServiceTax hotelServiceTax) {
		this.hotelServiceTax = hotelServiceTax;
	}

	public BigDecimal getTotalRoomPrice() {
		return totalRoomPrice;
	}

	public void setTotalRoomPrice(BigDecimal totalRoomPrice) {
		this.totalRoomPrice = totalRoomPrice;
	}

	public BigDecimal getApiPublishedPriceTotal() {
		return apiPublishedPriceTotal;
	}

	public void setApiPublishedPriceTotal(BigDecimal apiPublishedPriceTotal) {
		this.apiPublishedPriceTotal = apiPublishedPriceTotal;
	}

	public BigDecimal getTotalTax() {
		return totalTax;
	}

	public void setTotalTax(BigDecimal totalTax) {
		this.totalTax = totalTax;
	}

	public BigDecimal getTotalDiscount() {
		return totalDiscount;
	}

	public void setTotalDiscount(BigDecimal totalDiscount) {
		this.totalDiscount = totalDiscount;
	}




	/**
	 * @param discounts the discounts to set
	 */
	public void setDiscounts(List<AmountType.Discount> discounts) {
		this.discounts = discounts;
	}

	/**
	 * Gets the value of the discounts property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the discounts property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getDiscounts().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link AmountType.Discount }
	 *
	 *
	 */
	public List<AmountType.Discount> getDiscounts() {
		if (discounts == null) {
			discounts = new ArrayList<AmountType.Discount>();
		}
		return this.discounts;
	}


	public BigDecimal getTotalExtraGuestCharge() {
		return totalExtraGuestCharge;
	}

	public void setTotalExtraGuestCharge(BigDecimal totalExtraGuestCharge) {
		this.totalExtraGuestCharge = totalExtraGuestCharge;
	}

	public BigDecimal getTotalChildCharge() {
		return totalChildCharge;
	}

	public void setTotalChildCharge(BigDecimal totalChildCharge) {
		this.totalChildCharge = totalChildCharge;
	}

	public BigDecimal getTotalOtherCharges() {
		return totalOtherCharges;
	}

	public void setTotalOtherCharges(BigDecimal totalOtherCharges) {
		this.totalOtherCharges = totalOtherCharges;
	}

	public BigDecimal getTotalOfferedPrice() {
		return totalOfferedPrice;
	}

	public void setTotalOfferedPrice(BigDecimal totalOfferedPrice) {
		this.totalOfferedPrice = totalOfferedPrice;
	}

	public BigDecimal getTotalAgentCommission() {
		return totalAgentCommission;
	}

	public void setTotalAgentCommission(BigDecimal totalAgentCommission) {
		this.totalAgentCommission = totalAgentCommission;
	}

	public BigDecimal getTotalAgentMarkUp() {
		return totalAgentMarkUp;
	}

	public void setTotalAgentMarkUp(BigDecimal totalAgentMarkUp) {
		this.totalAgentMarkUp = totalAgentMarkUp;
	}

	public BigDecimal getTotalServiceTax() {
		return totalServiceTax;
	}

	public void setTotalServiceTax(BigDecimal totalServiceTax) {
		this.totalServiceTax = totalServiceTax;
	}

	public BigDecimal getTotalTDS() {
		return totalTDS;
	}

	public void setTotalTDS(BigDecimal totalTDS) {
		this.totalTDS = totalTDS;
	}

	public BigDecimal getTotalAmountPayable() {
		return totalAmountPayable;
	}

	public void setTotalAmountPayable(BigDecimal totalAmountPayable) {
		this.totalAmountPayable = totalAmountPayable;
	}

	@XmlAttribute(name = "MarkUpAmounts")
	protected List<BigDecimal> markUpAmounts;



	public List<BigDecimal> getMarkUpAmounts() {
		return markUpAmounts;
	}

	public void setMarkUpAmounts(List<BigDecimal> markUpAmounts) {
		this.markUpAmounts = markUpAmounts;
	}



	/**
	 * Gets the value of the taxes property.
	 *
	 * @return
	 *     possible object is
	 *     {@link TaxesType }
	 *
	 */
	public TaxesType getTaxes() {
		return taxes;
	}

	/**
	 * Sets the value of the taxes property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link TaxesType }
	 *
	 */
	public void setTaxes(TaxesType value) {
		this.taxes = value;
	}

	/**
	 * Gets the value of the additionalFeesExcludedIndicator property.
	 *
	 * @return
	 *     possible object is
	 *     {@link Boolean }
	 *
	 */
	public Boolean isAdditionalFeesExcludedIndicator() {
		return additionalFeesExcludedIndicator;
	}

	/**
	 * Sets the value of the additionalFeesExcludedIndicator property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link Boolean }
	 *
	 */
	public void setAdditionalFeesExcludedIndicator(Boolean value) {
		this.additionalFeesExcludedIndicator = value;
	}

	/**
	 * Gets the value of the amountAfterTax property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getAmountAfterTax() {
		return amountAfterTax;
	}

	/**
	 * Sets the value of the amountAfterTax property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setAmountAfterTax(BigDecimal value) {
		this.amountAfterTax = value;
	}

	/**
	 * Gets the value of the amountBeforeTax property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getAmountBeforeTax() {
		return amountBeforeTax;
	}

	/**
	 * Sets the value of the amountBeforeTax property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setAmountBeforeTax(BigDecimal value) {
		this.amountBeforeTax = value;
	}

	/**
	 * Gets the value of the amountIncludingMarkup property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getAmountIncludingMarkup() {
		return amountIncludingMarkup;
	}

	/**
	 * Sets the value of the amountIncludingMarkup property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setAmountIncludingMarkup(BigDecimal value) {
		this.amountIncludingMarkup = value;
	}

	/**
	 * Gets the value of the rateOverrideIndicator property.
	 *
	 * @return
	 *     possible object is
	 *     {@link Boolean }
	 *
	 */
	public Boolean isRateOverrideIndicator() {
		return rateOverrideIndicator;
	}

	/**
	 * Sets the value of the rateOverrideIndicator property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link Boolean }
	 *
	 */
	public void setRateOverrideIndicator(Boolean value) {
		this.rateOverrideIndicator = value;
	}

	/**
	 * Gets the value of the serviceOverrideIndicator property.
	 *
	 * @return
	 *     possible object is
	 *     {@link Boolean }
	 *
	 */
	public Boolean isServiceOverrideIndicator() {
		return serviceOverrideIndicator;
	}

	/**
	 * Sets the value of the serviceOverrideIndicator property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link Boolean }
	 *
	 */
	public void setServiceOverrideIndicator(Boolean value) {
		this.serviceOverrideIndicator = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the editCommission property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getEditCommission() {
		return editCommission;
	}

	/**
	 * Sets the value of the editCommission property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setEditCommission(BigDecimal value) {
		this.editCommission = value;
	}

	/**
	 * Gets the value of the editNetRate property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getEditNetRate() {
		return editNetRate;
	}

	/**
	 * Sets the value of the editNetRate property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setEditNetRate(BigDecimal value) {
		this.editNetRate = value;
	}

	/**
	 * Gets the value of the editSellRate property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getEditSellRate() {
		return editSellRate;
	}

	/**
	 * Sets the value of the editSellRate property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setEditSellRate(BigDecimal value) {
		this.editSellRate = value;
	}

	/**
	 * Gets the value of the editServiceCharge property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getEditServiceCharge() {
		return editServiceCharge;
	}

	/**
	 * Sets the value of the editServiceCharge property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setEditServiceCharge(BigDecimal value) {
		this.editServiceCharge = value;
	}

	/**
	 * Gets the value of the editServiceTax property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getEditServiceTax() {
		return editServiceTax;
	}

	/**
	 * Sets the value of the editServiceTax property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setEditServiceTax(BigDecimal value) {
		this.editServiceTax = value;
	}

	/**
	 * Gets the value of the editTotalTax property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getEditTotalTax() {
		return editTotalTax;
	}

	/**
	 * Sets the value of the editTotalTax property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setEditTotalTax(BigDecimal value) {
		this.editTotalTax = value;
	}

	/**
	 * Gets the value of the currencyCode property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getCurrencyCode() {
		return currencyCode;
	}

	/**
	 * Sets the value of the currencyCode property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setCurrencyCode(String value) {
		this.currencyCode = value;
	}

	/**
	 * Gets the value of the decimalPlaces property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *
	 */
	public BigInteger getDecimalPlaces() {
		return decimalPlaces;
	}

	/**
	 * Sets the value of the decimalPlaces property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *
	 */
	public void setDecimalPlaces(BigInteger value) {
		this.decimalPlaces = value;
	}

}
