//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.09 at 04:51:51 PM IST 
//


package com.tayyarah.hotel.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonInclude;


/**
 * <p>Java class for LoyaltyPointsAccrualsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoyaltyPointsAccrualsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SelectedLoyalty" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                 &lt;/sequence>
 *                 &lt;attribute name="AccountID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="BonusCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PointsEarned" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ProgramCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ReservationActionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SelectedLoyaltyRPH" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoyaltyPointsAccrualsType", propOrder = {
    "selectedLoyalties"
})
public class LoyaltyPointsAccrualsType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "SelectedLoyalty", required = true)
    protected List<LoyaltyPointsAccrualsType.SelectedLoyalty> selectedLoyalties;

    /**
     * Gets the value of the selectedLoyalties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedLoyalties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedLoyalties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoyaltyPointsAccrualsType.SelectedLoyalty }
     * 
     * 
     */
    public List<LoyaltyPointsAccrualsType.SelectedLoyalty> getSelectedLoyalties() {
        if (selectedLoyalties == null) {
            selectedLoyalties = new ArrayList<LoyaltyPointsAccrualsType.SelectedLoyalty>();
        }
        return this.selectedLoyalties;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *       &lt;/sequence>
     *       &lt;attribute name="AccountID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="BonusCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PointsEarned" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ProgramCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ReservationActionType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SelectedLoyaltyRPH" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SelectedLoyalty
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlAttribute(name = "AccountID")
        protected String accountID;
        @XmlAttribute(name = "BonusCode")
        protected String bonusCode;
        @XmlAttribute(name = "PointsEarned")
        protected String pointsEarned;
        @XmlAttribute(name = "ProgramCode")
        protected String programCode;
        @XmlAttribute(name = "ReservationActionType")
        protected String reservationActionType;
        @XmlAttribute(name = "SelectedLoyaltyRPH")
        protected String selectedLoyaltyRPH;

        /**
         * Gets the value of the accountID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountID() {
            return accountID;
        }

        /**
         * Sets the value of the accountID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountID(String value) {
            this.accountID = value;
        }

        /**
         * Gets the value of the bonusCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBonusCode() {
            return bonusCode;
        }

        /**
         * Sets the value of the bonusCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBonusCode(String value) {
            this.bonusCode = value;
        }

        /**
         * Gets the value of the pointsEarned property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPointsEarned() {
            return pointsEarned;
        }

        /**
         * Sets the value of the pointsEarned property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPointsEarned(String value) {
            this.pointsEarned = value;
        }

        /**
         * Gets the value of the programCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProgramCode() {
            return programCode;
        }

        /**
         * Sets the value of the programCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProgramCode(String value) {
            this.programCode = value;
        }

        /**
         * Gets the value of the reservationActionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReservationActionType() {
            return reservationActionType;
        }

        /**
         * Sets the value of the reservationActionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReservationActionType(String value) {
            this.reservationActionType = value;
        }

        /**
         * Gets the value of the selectedLoyaltyRPH property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSelectedLoyaltyRPH() {
            return selectedLoyaltyRPH;
        }

        /**
         * Sets the value of the selectedLoyaltyRPH property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSelectedLoyaltyRPH(String value) {
            this.selectedLoyaltyRPH = value;
        }

    }

}
