
package com.tayyarah.api.insurance.trawelltag.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgentAPIV2Soap", targetNamespace = "https://karvatgroup.in/trawelltag/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgentAPIV2Soap {


    /**
     * 
     * @param ref
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreatePolicy", action = "https://karvatgroup.in/trawelltag/CreatePolicy")
    @WebResult(name = "CreatePolicyResult", targetNamespace = "https://karvatgroup.in/trawelltag/")
    @RequestWrapper(localName = "CreatePolicy", targetNamespace = "https://karvatgroup.in/trawelltag/", className = "https.karvatgroup_in.trawelltag.CreatePolicy")
    @ResponseWrapper(localName = "CreatePolicyResponse", targetNamespace = "https://karvatgroup.in/trawelltag/", className = "https.karvatgroup_in.trawelltag.CreatePolicyResponse")
    public String createPolicy(
        @WebParam(name = "Data", targetNamespace = "https://karvatgroup.in/trawelltag/")
        String data,
        @WebParam(name = "Ref", targetNamespace = "https://karvatgroup.in/trawelltag/")
        String ref);

    /**
     * 
     * @param ref
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EndorsementRequestsecondcall", action = "https://karvatgroup.in/trawelltag/EndorsementRequestsecondcall")
    @WebResult(name = "EndorsementRequestsecondcallResult", targetNamespace = "https://karvatgroup.in/trawelltag/")
    @RequestWrapper(localName = "EndorsementRequestsecondcall", targetNamespace = "https://karvatgroup.in/trawelltag/", className = "https.karvatgroup_in.trawelltag.EndorsementRequestsecondcall")
    @ResponseWrapper(localName = "EndorsementRequestsecondcallResponse", targetNamespace = "https://karvatgroup.in/trawelltag/", className = "https.karvatgroup_in.trawelltag.EndorsementRequestsecondcallResponse")
    public String endorsementRequestsecondcall(
        @WebParam(name = "Data", targetNamespace = "https://karvatgroup.in/trawelltag/")
        String data,
        @WebParam(name = "Ref", targetNamespace = "https://karvatgroup.in/trawelltag/")
        String ref);

    /**
     * 
     * @param ref
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EndorsementRequestfirstcall", action = "https://karvatgroup.in/trawelltag/EndorsementRequestfirstcall")
    @WebResult(name = "EndorsementRequestfirstcallResult", targetNamespace = "https://karvatgroup.in/trawelltag/")
    @RequestWrapper(localName = "EndorsementRequestfirstcall", targetNamespace = "https://karvatgroup.in/trawelltag/", className = "https.karvatgroup_in.trawelltag.EndorsementRequestfirstcall")
    @ResponseWrapper(localName = "EndorsementRequestfirstcallResponse", targetNamespace = "https://karvatgroup.in/trawelltag/", className = "https.karvatgroup_in.trawelltag.EndorsementRequestfirstcallResponse")
    public String endorsementRequestfirstcall(
        @WebParam(name = "Data", targetNamespace = "https://karvatgroup.in/trawelltag/")
        String data,
        @WebParam(name = "Ref", targetNamespace = "https://karvatgroup.in/trawelltag/")
        String ref);

}
