//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 11:55:50 AM IST 
//


package com.tayyarah.api.hotel.rezlive.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArrivalDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GuestNationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SearchSessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Hotels">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Hotel" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Rating" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ThumbImages" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="RoomDetails">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RoomDetail" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                                 &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ipaddress" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "arrivalDate",
    "departureDate",
    "currency",
    "guestNationality",
    "searchSessionId",
    "hotels"
})
@XmlRootElement(name = "HotelFindResponse")
public class HotelFindResponse
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "ArrivalDate", required = true)
    protected String arrivalDate;
    @XmlElement(name = "DepartureDate", required = true)
    protected String departureDate;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "GuestNationality", required = true)
    protected String guestNationality;
    @XmlElement(name = "SearchSessionId", required = true)
    protected String searchSessionId;
    @XmlElement(name = "Hotels", required = true)
    protected HotelFindResponse.Hotels hotels;
    @XmlAttribute(name = "time")
    protected String time;
    @XmlAttribute(name = "ipaddress")
    protected String ipaddress;
    @XmlAttribute(name = "count")
    protected Integer count;

    /**
     * Gets the value of the arrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalDate() {
        return arrivalDate;
    }

    /**
     * Sets the value of the arrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalDate(String value) {
        this.arrivalDate = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureDate(String value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the guestNationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuestNationality() {
        return guestNationality;
    }

    /**
     * Sets the value of the guestNationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuestNationality(String value) {
        this.guestNationality = value;
    }

    /**
     * Gets the value of the searchSessionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchSessionId() {
        return searchSessionId;
    }

    /**
     * Sets the value of the searchSessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchSessionId(String value) {
        this.searchSessionId = value;
    }

    /**
     * Gets the value of the hotels property.
     * 
     * @return
     *     possible object is
     *     {@link HotelFindResponse.Hotels }
     *     
     */
    public HotelFindResponse.Hotels getHotels() {
        return hotels;
    }

    /**
     * Sets the value of the hotels property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelFindResponse.Hotels }
     *     
     */
    public void setHotels(HotelFindResponse.Hotels value) {
        this.hotels = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the ipaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * Sets the value of the ipaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpaddress(String value) {
        this.ipaddress = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCount(Integer value) {
        this.count = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Hotel" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Rating" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ThumbImages" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="RoomDetails">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RoomDetail" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                                       &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hotels"
    })
    public static class Hotels
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(name = "Hotel")
        protected List<HotelFindResponse.Hotels.Hotel> hotels;

        /**
         * Gets the value of the hotels property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hotels property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHotels().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HotelFindResponse.Hotels.Hotel }
         * 
         * 
         */
        public List<HotelFindResponse.Hotels.Hotel> getHotels() {
            if (hotels == null) {
                hotels = new ArrayList<HotelFindResponse.Hotels.Hotel>();
            }
            return this.hotels;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Rating" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ThumbImages" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="RoomDetails">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RoomDetail" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "name",
            "rating",
            "thumbImages",
            "price",
            "roomDetails"
        })
        public static class Hotel
            implements Serializable
        {

            private final static long serialVersionUID = -1L;
            @XmlElement(name = "Id", required = true)
            protected String id;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Rating")
            protected int rating;
            @XmlElement(name = "ThumbImages", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String thumbImages;
            @XmlElement(name = "Price", required = true)
            protected BigDecimal price;
            @XmlElement(name = "RoomDetails", required = true)
            protected HotelFindResponse.Hotels.Hotel.RoomDetails roomDetails;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the rating property.
             * 
             */
            public int getRating() {
                return rating;
            }

            /**
             * Sets the value of the rating property.
             * 
             */
            public void setRating(int value) {
                this.rating = value;
            }

            /**
             * Gets the value of the thumbImages property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getThumbImages() {
                return thumbImages;
            }

            /**
             * Sets the value of the thumbImages property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setThumbImages(String value) {
                this.thumbImages = value;
            }

            /**
             * Gets the value of the price property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPrice(BigDecimal value) {
                this.price = value;
            }

            /**
             * Gets the value of the roomDetails property.
             * 
             * @return
             *     possible object is
             *     {@link HotelFindResponse.Hotels.Hotel.RoomDetails }
             *     
             */
            public HotelFindResponse.Hotels.Hotel.RoomDetails getRoomDetails() {
                return roomDetails;
            }

            /**
             * Sets the value of the roomDetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link HotelFindResponse.Hotels.Hotel.RoomDetails }
             *     
             */
            public void setRoomDetails(HotelFindResponse.Hotels.Hotel.RoomDetails value) {
                this.roomDetails = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RoomDetail" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "roomDetails"
            })
            public static class RoomDetails
                implements Serializable
            {

                private final static long serialVersionUID = -1L;
                @XmlElement(name = "RoomDetail")
                protected List<HotelFindResponse.Hotels.Hotel.RoomDetails.RoomDetail> roomDetails;

                /**
                 * Gets the value of the roomDetails property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the roomDetails property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getRoomDetails().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link HotelFindResponse.Hotels.Hotel.RoomDetails.RoomDetail }
                 * 
                 * 
                 */
                public List<HotelFindResponse.Hotels.Hotel.RoomDetails.RoomDetail> getRoomDetails() {
                    if (roomDetails == null) {
                        roomDetails = new ArrayList<HotelFindResponse.Hotels.Hotel.RoomDetails.RoomDetail>();
                    }
                    return this.roomDetails;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "type",
                    "bookingKey",
                    "adults",
                    "children",
                    "childrenAges",
                    "totalRooms",
                    "totalRate",
                    "roomDescription",
                    "termsAndConditions"
                })
                public static class RoomDetail
                    implements Serializable
                {

                    @Override
					public String toString() {
						return "RoomDetail [type=" + type + ", bookingKey=" + bookingKey + ", adults=" + adults
								+ ", children=" + children + ", childrenAges=" + childrenAges + ", totalRooms="
								+ totalRooms + ", totalRate=" + totalRate + ", roomDescription=" + roomDescription
								+ ", termsAndConditions=" + termsAndConditions + "]";
					}

					private final static long serialVersionUID = -1L;
                    @XmlElement(name = "Type", required = true)
                    protected String type;
                    @XmlElement(name = "BookingKey", required = true)
                    protected String bookingKey;
                    @XmlElement(name = "Adults")
                    protected String adults;
                    @XmlElement(name = "Children")
                    protected String children;
                    @XmlElement(name = "ChildrenAges")
                    protected String childrenAges;
                    @XmlElement(name = "TotalRooms")
                    protected String totalRooms;
                    @XmlElement(name = "TotalRate", required = true)
                    protected String totalRate;
                    @XmlElement(name = "RoomDescription", required = true)
                    protected String roomDescription;
                    @XmlElement(name = "TermsAndConditions", required = true)
                    protected String termsAndConditions;

                 /*   @XmlCDATA
                    private String name;*/
                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    /**
                     * Gets the value of the bookingKey property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBookingKey() {
                        return bookingKey;
                    }

                    /**
                     * Sets the value of the bookingKey property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBookingKey(String value) {
                        this.bookingKey = value;
                    }

                    /**
                     * Gets the value of the adults property.
                     * 
                     */
                    public String getAdults() {
                        return adults;
                    }

                    /**
                     * Sets the value of the adults property.
                     * 
                     */
                    public void setAdults(String value) {
                        this.adults = value;
                    }

                    /**
                     * Gets the value of the children property.
                     * 
                     */
                    public String getChildren() {
                        return children;
                    }

                    /**
                     * Sets the value of the children property.
                     * 
                     */
                    public void setChildren(String value) {
                        this.children = value;
                    }

                    /**
                     * Gets the value of the childrenAges property.
                     * 
                     */
                    public String getChildrenAges() {
                        return childrenAges;
                    }

                    /**
                     * Sets the value of the childrenAges property.
                     * 
                     */
                    public void setChildrenAges(String value) {
                        this.childrenAges = value;
                    }

                    /**
                     * Gets the value of the totalRooms property.
                     * 
                     */
                    public String getTotalRooms() {
                        return totalRooms;
                    }

                    /**
                     * Sets the value of the totalRooms property.
                     * 
                     */
                    public void setTotalRooms(String value) {
                        this.totalRooms = value;
                    }

                    /**
                     * Gets the value of the totalRate property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public String getTotalRate() {
                        return totalRate;
                    }

                    /**
                     * Sets the value of the totalRate property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setTotalRate(String value) {
                        this.totalRate = value;
                    }

                    /**
                     * Gets the value of the roomDescription property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRoomDescription() {
                        return roomDescription;
                    }

                    /**
                     * Sets the value of the roomDescription property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRoomDescription(String value) {
                        this.roomDescription = value;
                    }

                    /**
                     * Gets the value of the termsAndConditions property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTermsAndConditions() {
                        return termsAndConditions;
                    }

                    /**
                     * Sets the value of the termsAndConditions property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTermsAndConditions(String value) {
                        this.termsAndConditions = value;
                    }

                }

            }

        }

    }

}
