//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 02:20:34 PM IST 
//


package com.tayyarah.api.hotel.rezlive.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PreBookingRequest">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Authentication">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AgentCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PreBooking">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ArrivalDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="GuestNationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="HotelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RoomDetails">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RoomDetail">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                                 &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CancellationInformations">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CancellationInformation" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                                 &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Info" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PreBookingDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BookingBeforePrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="BookingAfterPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="Difference" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="AgentBalance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="AgentCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"error",
    "preBookingRequest",
    "preBookingDetails"
})
@XmlRootElement(name = "PreBookingResponse")
public class PreBookingResponse
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "Error", required = true)
    protected String error;
    public String getError() {
		return error;
	}

	public void setError(String error) {
		this.error = error;
	}


	@XmlElement(name = "PreBookingRequest", required = true)
    protected PreBookingResponse.PreBookingRequest preBookingRequest;
    @XmlElement(name = "PreBookingDetails", required = true)
    protected PreBookingResponse.PreBookingDetails preBookingDetails;

    /**
     * Gets the value of the preBookingRequest property.
     * 
     * @return
     *     possible object is
     *     {@link PreBookingResponse.PreBookingRequest }
     *     
     */
    public PreBookingResponse.PreBookingRequest getPreBookingRequest() {
        return preBookingRequest;
    }

    /**
     * Sets the value of the preBookingRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreBookingResponse.PreBookingRequest }
     *     
     */
    public void setPreBookingRequest(PreBookingResponse.PreBookingRequest value) {
        this.preBookingRequest = value;
    }

    /**
     * Gets the value of the preBookingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PreBookingResponse.PreBookingDetails }
     *     
     */
    public PreBookingResponse.PreBookingDetails getPreBookingDetails() {
        return preBookingDetails;
    }

    /**
     * Sets the value of the preBookingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreBookingResponse.PreBookingDetails }
     *     
     */
    public void setPreBookingDetails(PreBookingResponse.PreBookingDetails value) {
        this.preBookingDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BookingBeforePrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="BookingAfterPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="Difference" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="AgentBalance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="AgentCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "bookingBeforePrice",
        "bookingAfterPrice",
        "difference",
        "agentBalance",
        "agentCurrency"
    })
    public static class PreBookingDetails
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "BookingBeforePrice", required = true)
        protected BigDecimal bookingBeforePrice;
        @XmlElement(name = "BookingAfterPrice", required = true)
        protected BigDecimal bookingAfterPrice;
        @XmlElement(name = "Difference", required = true)
        protected BigDecimal difference;
        @XmlElement(name = "AgentBalance", required = true)
        protected BigDecimal agentBalance;
        @XmlElement(name = "AgentCurrency", required = true)
        protected String agentCurrency;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the bookingBeforePrice property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBookingBeforePrice() {
            return bookingBeforePrice;
        }

        /**
         * Sets the value of the bookingBeforePrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBookingBeforePrice(BigDecimal value) {
            this.bookingBeforePrice = value;
        }

        /**
         * Gets the value of the bookingAfterPrice property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBookingAfterPrice() {
            return bookingAfterPrice;
        }

        /**
         * Sets the value of the bookingAfterPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBookingAfterPrice(BigDecimal value) {
            this.bookingAfterPrice = value;
        }

        /**
         * Gets the value of the difference property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDifference() {
            return difference;
        }

        /**
         * Sets the value of the difference property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDifference(BigDecimal value) {
            this.difference = value;
        }

        /**
         * Gets the value of the agentBalance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAgentBalance() {
            return agentBalance;
        }

        /**
         * Sets the value of the agentBalance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAgentBalance(BigDecimal value) {
            this.agentBalance = value;
        }

        /**
         * Gets the value of the agentCurrency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgentCurrency() {
            return agentCurrency;
        }

        /**
         * Sets the value of the agentCurrency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgentCurrency(String value) {
            this.agentCurrency = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Authentication">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AgentCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PreBooking">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ArrivalDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="GuestNationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="HotelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RoomDetails">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RoomDetail">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                                       &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CancellationInformations">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CancellationInformation" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                                       &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Info" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "authentication",
        "preBooking"
    })
    public static class PreBookingRequest
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(name = "Authentication", required = true)
        protected PreBookingResponse.PreBookingRequest.Authentication authentication;
        @XmlElement(name = "PreBooking", required = true)
        protected PreBookingResponse.PreBookingRequest.PreBooking preBooking;

        /**
         * Gets the value of the authentication property.
         * 
         * @return
         *     possible object is
         *     {@link PreBookingResponse.PreBookingRequest.Authentication }
         *     
         */
        public PreBookingResponse.PreBookingRequest.Authentication getAuthentication() {
            return authentication;
        }

        /**
         * Sets the value of the authentication property.
         * 
         * @param value
         *     allowed object is
         *     {@link PreBookingResponse.PreBookingRequest.Authentication }
         *     
         */
        public void setAuthentication(PreBookingResponse.PreBookingRequest.Authentication value) {
            this.authentication = value;
        }

        /**
         * Gets the value of the preBooking property.
         * 
         * @return
         *     possible object is
         *     {@link PreBookingResponse.PreBookingRequest.PreBooking }
         *     
         */
        public PreBookingResponse.PreBookingRequest.PreBooking getPreBooking() {
            return preBooking;
        }

        /**
         * Sets the value of the preBooking property.
         * 
         * @param value
         *     allowed object is
         *     {@link PreBookingResponse.PreBookingRequest.PreBooking }
         *     
         */
        public void setPreBooking(PreBookingResponse.PreBookingRequest.PreBooking value) {
            this.preBooking = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AgentCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "agentCode",
            "userName",
            "password"
        })
        public static class Authentication
            implements Serializable
        {

            private final static long serialVersionUID = -1L;
            @XmlElement(name = "AgentCode", required = true)
            protected String agentCode;
            @XmlElement(name = "UserName", required = true)
            protected String userName;
            @XmlElement(name = "Password", required = true)
            protected String password;

            /**
             * Gets the value of the agentCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAgentCode() {
                return agentCode;
            }

            /**
             * Sets the value of the agentCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAgentCode(String value) {
                this.agentCode = value;
            }

            /**
             * Gets the value of the userName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserName() {
                return userName;
            }

            /**
             * Sets the value of the userName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserName(String value) {
                this.userName = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ArrivalDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GuestNationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="HotelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RoomDetails">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RoomDetail">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                             &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CancellationInformations">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CancellationInformation" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                             &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Info" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "arrivalDate",
            "departureDate",
            "currency",
            "guestNationality",
            "countryCode",
            "city",
            "hotelId",
            "roomDetails",
            "cancellationInformations"
        })
        public static class PreBooking
            implements Serializable
        {

            private final static long serialVersionUID = -1L;
            @XmlElement(name = "ArrivalDate", required = true)
            protected String arrivalDate;
            @XmlElement(name = "DepartureDate", required = true)
            protected String departureDate;
            @XmlElement(name = "Currency", required = true)
            protected String currency;
            @XmlElement(name = "GuestNationality", required = true)
            protected String guestNationality;
            @XmlElement(name = "CountryCode", required = true)
            protected String countryCode;
            @XmlElement(name = "City", required = true)
            protected String city;
            @XmlElement(name = "HotelId", required = true)
            protected String hotelId;
            @XmlElement(name = "RoomDetails", required = true)
            protected PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails roomDetails;
            @XmlElement(name = "CancellationInformations", required = true)
            protected PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations cancellationInformations;

            /**
             * Gets the value of the arrivalDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArrivalDate() {
                return arrivalDate;
            }

            /**
             * Sets the value of the arrivalDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArrivalDate(String value) {
                this.arrivalDate = value;
            }

            /**
             * Gets the value of the departureDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDepartureDate() {
                return departureDate;
            }

            /**
             * Sets the value of the departureDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDepartureDate(String value) {
                this.departureDate = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the guestNationality property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGuestNationality() {
                return guestNationality;
            }

            /**
             * Sets the value of the guestNationality property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGuestNationality(String value) {
                this.guestNationality = value;
            }

            /**
             * Gets the value of the countryCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryCode() {
                return countryCode;
            }

            /**
             * Sets the value of the countryCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryCode(String value) {
                this.countryCode = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the hotelId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHotelId() {
                return hotelId;
            }

            /**
             * Sets the value of the hotelId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHotelId(String value) {
                this.hotelId = value;
            }

            /**
             * Gets the value of the roomDetails property.
             * 
             * @return
             *     possible object is
             *     {@link PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails }
             *     
             */
            public PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails getRoomDetails() {
                return roomDetails;
            }

            /**
             * Sets the value of the roomDetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails }
             *     
             */
            public void setRoomDetails(PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails value) {
                this.roomDetails = value;
            }

            /**
             * Gets the value of the cancellationInformations property.
             * 
             * @return
             *     possible object is
             *     {@link PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations }
             *     
             */
            public PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations getCancellationInformations() {
                return cancellationInformations;
            }

            /**
             * Sets the value of the cancellationInformations property.
             * 
             * @param value
             *     allowed object is
             *     {@link PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations }
             *     
             */
            public void setCancellationInformations(PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations value) {
                this.cancellationInformations = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CancellationInformation" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Info" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cancellationInformations",
                "info"
            })
            public static class CancellationInformations
                implements Serializable
            {

                private final static long serialVersionUID = -1L;
                @XmlElement(name = "CancellationInformation")
                protected List<PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations.CancellationInformation> cancellationInformations;
                @XmlElement(name = "Info", required = true)
                protected String info;

                /**
                 * Gets the value of the cancellationInformations property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the cancellationInformations property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCancellationInformations().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations.CancellationInformation }
                 * 
                 * 
                 */
                public List<PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations.CancellationInformation> getCancellationInformations() {
                    if (cancellationInformations == null) {
                        cancellationInformations = new ArrayList<PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations.CancellationInformation>();
                    }
                    return this.cancellationInformations;
                }

                /**
                 * Gets the value of the info property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInfo() {
                    return info;
                }

                /**
                 * Sets the value of the info property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInfo(String value) {
                    this.info = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "startDate",
                    "endDate",
                    "chargeType",
                    "chargeAmount",
                    "currency"
                })
                public static class CancellationInformation
                    implements Serializable
                {

                    private final static long serialVersionUID = -1L;
                    @XmlElement(name = "StartDate", required = true)
                    protected String startDate;
                    @XmlElement(name = "EndDate", required = true)
                    protected String endDate;
                    @XmlElement(name = "ChargeType", required = true)
                    protected String chargeType;
                    @XmlElement(name = "ChargeAmount", required = true)
                    protected BigDecimal chargeAmount;
                    @XmlElement(name = "Currency", required = true)
                    protected String currency;

                    /**
                     * Gets the value of the startDate property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getStartDate() {
                        return startDate;
                    }

                    /**
                     * Sets the value of the startDate property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setStartDate(String value) {
                        this.startDate = value;
                    }

                    /**
                     * Gets the value of the endDate property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getEndDate() {
                        return endDate;
                    }

                    /**
                     * Sets the value of the endDate property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setEndDate(String value) {
                        this.endDate = value;
                    }

                    /**
                     * Gets the value of the chargeType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getChargeType() {
                        return chargeType;
                    }

                    /**
                     * Sets the value of the chargeType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setChargeType(String value) {
                        this.chargeType = value;
                    }

                    /**
                     * Gets the value of the chargeAmount property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getChargeAmount() {
                        return chargeAmount;
                    }

                    /**
                     * Sets the value of the chargeAmount property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setChargeAmount(BigDecimal value) {
                        this.chargeAmount = value;
                    }

                    /**
                     * Gets the value of the currency property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCurrency() {
                        return currency;
                    }

                    /**
                     * Sets the value of the currency property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCurrency(String value) {
                        this.currency = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RoomDetail">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *                   &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "roomDetail"
            })
            public static class RoomDetails
                implements Serializable
            {

                private final static long serialVersionUID = -1L;
                @XmlElement(name = "RoomDetail", required = true)
                protected PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails.RoomDetail roomDetail;

                /**
                 * Gets the value of the roomDetail property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails.RoomDetail }
                 *     
                 */
                public PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails.RoomDetail getRoomDetail() {
                    return roomDetail;
                }

                /**
                 * Sets the value of the roomDetail property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails.RoomDetail }
                 *     
                 */
                public void setRoomDetail(PreBookingResponse.PreBookingRequest.PreBooking.RoomDetails.RoomDetail value) {
                    this.roomDetail = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="BookingKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Adults" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="TotalRooms" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="TotalRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                 *         &lt;element name="RoomDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="TermsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "type",
                    "bookingKey",
                    "adults",
                    "children",
                    "childrenAges",
                    "totalRooms",
                    "totalRate",
                    "roomDescription",
                    "termsAndConditions"
                })
                public static class RoomDetail
                    implements Serializable
                {

                    private final static long serialVersionUID = -1L;
                    @XmlElement(name = "Type", required = true)
                    protected String type;
                    @XmlElement(name = "BookingKey", required = true)
                    protected String bookingKey;
                    @XmlElement(name = "Adults")
                    protected int adults;
                    @XmlElement(name = "Children")
                    protected int children;
                    @XmlElement(name = "ChildrenAges")
                    protected int childrenAges;
                    @XmlElement(name = "TotalRooms")
                    protected int totalRooms;
                    @XmlElement(name = "TotalRate", required = true)
                    protected BigDecimal totalRate;
                    @XmlElement(name = "RoomDescription", required = true)
                    protected String roomDescription;
                    @XmlElement(name = "TermsAndConditions", required = true)
                    protected String termsAndConditions;

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    /**
                     * Gets the value of the bookingKey property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBookingKey() {
                        return bookingKey;
                    }

                    /**
                     * Sets the value of the bookingKey property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBookingKey(String value) {
                        this.bookingKey = value;
                    }

                    /**
                     * Gets the value of the adults property.
                     * 
                     */
                    public int getAdults() {
                        return adults;
                    }

                    /**
                     * Sets the value of the adults property.
                     * 
                     */
                    public void setAdults(int value) {
                        this.adults = value;
                    }

                    /**
                     * Gets the value of the children property.
                     * 
                     */
                    public int getChildren() {
                        return children;
                    }

                    /**
                     * Sets the value of the children property.
                     * 
                     */
                    public void setChildren(int value) {
                        this.children = value;
                    }

                    /**
                     * Gets the value of the childrenAges property.
                     * 
                     */
                    public int getChildrenAges() {
                        return childrenAges;
                    }

                    /**
                     * Sets the value of the childrenAges property.
                     * 
                     */
                    public void setChildrenAges(int value) {
                        this.childrenAges = value;
                    }

                    /**
                     * Gets the value of the totalRooms property.
                     * 
                     */
                    public int getTotalRooms() {
                        return totalRooms;
                    }

                    /**
                     * Sets the value of the totalRooms property.
                     * 
                     */
                    public void setTotalRooms(int value) {
                        this.totalRooms = value;
                    }

                    /**
                     * Gets the value of the totalRate property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getTotalRate() {
                        return totalRate;
                    }

                    /**
                     * Sets the value of the totalRate property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setTotalRate(BigDecimal value) {
                        this.totalRate = value;
                    }

                    /**
                     * Gets the value of the roomDescription property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRoomDescription() {
                        return roomDescription;
                    }

                    /**
                     * Sets the value of the roomDescription property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRoomDescription(String value) {
                        this.roomDescription = value;
                    }

                    /**
                     * Gets the value of the termsAndConditions property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTermsAndConditions() {
                        return termsAndConditions;
                    }

                    /**
                     * Sets the value of the termsAndConditions property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTermsAndConditions(String value) {
                        this.termsAndConditions = value;
                    }

                }

            }

        }

    }

}
