//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.09 at 04:51:51 PM IST 
//


package com.tayyarah.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.tayyarah.api.hotel.rezlive.model.BookingResponse;
import com.tayyarah.api.hotel.rezlive.model.PreBookingResponse;
import com.tayyarah.common.model.CommissionDetails;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opentravel.org/OTA/2003/05}HotelResResponseType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OTA_HotelResRS")
public class OTAHotelResRS
extends HotelResResponseType
implements Serializable
{

	public CancellationInformations getCancellationInformations() {
		return cancellationInformations;
	}
	public void setCancellationInformations(CancellationInformations cancellationInformations) {
		this.cancellationInformations = cancellationInformations;
	}
	public String getBookingId() {
		return bookingId;
	}
	public void setBookingId(String bookingId) {
		this.bookingId = bookingId;
	}
	public String getBookingCode() {
		return bookingCode;
	}
	public void setBookingCode(String bookingCode) {
		this.bookingCode = bookingCode;
	}

	public BigDecimal getAgentBalance() {
		return agentBalance;
	}
	public void setAgentBalance(BigDecimal agentBalance) {
		this.agentBalance = agentBalance;
	}
	public String getAgentCurrency() {
		return agentCurrency;
	}
	public void setAgentCurrency(String agentCurrency) {
		this.agentCurrency = agentCurrency;
	}
	public PreBookingResponse getPreBookingResponse() {
		return preBookingResponse;
	}
	public void setPreBookingResponse(PreBookingResponse preBookingResponse) {
		this.preBookingResponse = preBookingResponse;
	}
	public BookingResponse getBookingResponse() {
		return bookingResponse;
	}
	public void setBookingResponse(BookingResponse bookingResponse) {
		this.bookingResponse = bookingResponse;
	}
	public OTAHotelResRS() {
		super();
		this.status = new APIStatus(APIStatus.STATUS_CODE_ERROR , APIStatus.STATUS_CODE_ERROR);
		// TODO Auto-generated constructor stub
	}
	private final static long serialVersionUID = -1L;
	private APIStatus status;

	private PreBookingResponse preBookingResponse;

	private BookingResponse bookingResponse;


	public APIStatus getStatus() {
		if(this.status == null)
			this.status = new APIStatus(APIStatus.STATUS_CODE_ERROR , APIStatus.STATUS_CODE_ERROR);
		return status;
	}
	public void setStatus(APIStatus status) {
		this.status = status;
	}
	
	 protected CancellationInformations cancellationInformations;

	
	@XmlElement(name = "BookingId", required = true)
	protected String bookingId;
	@XmlElement(name = "BookingCode", required = true)
	protected String bookingCode;
	@XmlElement(name = "BookingStatus", required = true)
	protected String bookingStatus;
	@XmlElement(name = "AgentBalance", required = true)
	protected BigDecimal agentBalance;
	@XmlElement(name = "AgentCurrency", required = true)
	protected String agentCurrency;


	@XmlAttribute(name = "ApiFinalPrice")
	protected BigDecimal apiFinalPrice;
	
	@XmlAttribute(name = "BaseFinalPrice")
	protected BigDecimal baseFinalPrice;
	
	@XmlAttribute(name = "BaseFinalPriceWithoutMarkup")
	protected BigDecimal baseFinalPriceWithoutMarkup;
	
	@XmlAttribute(name = "BookingFinalPrice")
	protected BigDecimal bookingFinalPrice;
	
	
	
	@XmlElement(name = "ConfirmationNo", required = true)
	protected String confirmationNo;
	
	@XmlAttribute(name = "isPriceChanged")
	protected boolean isPriceChanged;
	
	@XmlAttribute(name = "oldBookingFinalPrice")
	protected BigDecimal oldBookingFinalPrice;
	
	@XmlAttribute(name = "BookingPayablePrice")
	protected BigDecimal BookingPayablePrice;
	
	
	
	public BigDecimal getBookingPayablePrice() {
		return BookingPayablePrice;
	}
	public void setBookingPayablePrice(BigDecimal bookingPayablePrice) {
		BookingPayablePrice = bookingPayablePrice;
	}
	public BigDecimal getOldBookingFinalPrice() {
		return oldBookingFinalPrice;
	}
	public void setOldBookingFinalPrice(BigDecimal oldBookingFinalPrice) {
		this.oldBookingFinalPrice = oldBookingFinalPrice;
	}
	public boolean isPriceChanged() {
		return isPriceChanged;
	}
	public void setPriceChanged(boolean isPriceChanged) {
		this.isPriceChanged = isPriceChanged;
	}
	public String getConfirmationNo() {
		return confirmationNo;
	}
	public void setConfirmationNo(String confirmationNo) {
		this.confirmationNo = confirmationNo;
	}
	@XmlElement(name = "InvoiceNo", required = true)
	protected String invoiceNo;
	
	
	public String getInvoiceNo() {
		return invoiceNo;
	}
	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}
	public BigDecimal getApiFinalPrice() {
		return apiFinalPrice;
	}
	public void setApiFinalPrice(BigDecimal apiFinalPrice) {
		this.apiFinalPrice = apiFinalPrice;
	}
	public BigDecimal getBaseFinalPrice() {
		return baseFinalPrice;
	}
	public void setBaseFinalPrice(BigDecimal baseFinalPrice) {
		this.baseFinalPrice = baseFinalPrice;
	}
	public BigDecimal getBaseFinalPriceWithoutMarkup() {
		return baseFinalPriceWithoutMarkup;
	}
	public void setBaseFinalPriceWithoutMarkup(BigDecimal baseFinalPriceWithoutMarkup) {
		this.baseFinalPriceWithoutMarkup = baseFinalPriceWithoutMarkup;
	}
	public BigDecimal getBookingFinalPrice() {
		return bookingFinalPrice;
	}
	public void setBookingFinalPrice(BigDecimal bookingFinalPrice) {
		this.bookingFinalPrice = bookingFinalPrice;
	}

	private Map<String,BigDecimal> markupmap;
	private Map<String,CommissionDetails> commissionmap;
	public Map<String, BigDecimal> getMarkupmap() {
		return markupmap;
	}

	public void setMarkupmap(Map<String, BigDecimal> markupmap) {
		this.markupmap = markupmap;
	}

	public Map<String, CommissionDetails> getCommissionmap() {
		return commissionmap;
	}

	public void setCommissionmap(Map<String, CommissionDetails> commissionmap) {
		this.commissionmap = commissionmap;
	}


	public static class CancellationInformations
	implements Serializable
	{

		private final static long serialVersionUID = -1L;
		@XmlElement(name = "CancellationInformation")
		protected List<OTAHotelResRS.CancellationInformations.CancellationInformation> cancellationInformations;
		public void setCancellationInformations(
				List<OTAHotelResRS.CancellationInformations.CancellationInformation> cancellationInformations) {
			this.cancellationInformations = cancellationInformations;
		}


		@XmlElement(name = "Info", required = true)
		protected String info;

		/**
		 * Gets the value of the cancellationInformations property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the cancellationInformations property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getCancellationInformations().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link PreBookingResponse.PreBookingRequest.PreBooking.CancellationInformations.CancellationInformation }
		 * 
		 * 
		 */
		public List<OTAHotelResRS.CancellationInformations.CancellationInformation> getCancellationInformations() {
			if (cancellationInformations == null) {
				cancellationInformations = new ArrayList<OTAHotelResRS.CancellationInformations.CancellationInformation>();
			}
			return this.cancellationInformations;
		}

		/**
		 * Gets the value of the info property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 *     
		 */
		public String getInfo() {
			return info;
		}

		/**
		 * Sets the value of the info property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *     
		 */
		public void setInfo(String value) {
			this.info = value;
		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
		 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"startDate",
				"endDate",
				"chargeType",
				"chargeAmount",
				"currency"
		})
		public static class CancellationInformation
		implements Serializable
		{

			private final static long serialVersionUID = -1L;
			@XmlElement(name = "StartDate", required = true)
			protected String startDate;
			@XmlElement(name = "EndDate", required = true)
			protected String endDate;
			@XmlElement(name = "ChargeType", required = true)
			protected String chargeType;
			@XmlElement(name = "ChargeAmount", required = true)
			protected BigDecimal chargeAmount;
			@XmlElement(name = "Currency", required = true)
			protected String currency;

			/**
			 * Gets the value of the startDate property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link String }
			 *     
			 */
			public String getStartDate() {
				return startDate;
			}

			/**
			 * Sets the value of the startDate property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *     
			 */
			public void setStartDate(String value) {
				this.startDate = value;
			}

			/**
			 * Gets the value of the endDate property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link String }
			 *     
			 */
			public String getEndDate() {
				return endDate;
			}

			/**
			 * Sets the value of the endDate property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *     
			 */
			public void setEndDate(String value) {
				this.endDate = value;
			}

			/**
			 * Gets the value of the chargeType property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link String }
			 *     
			 */
			public String getChargeType() {
				return chargeType;
			}

			/**
			 * Sets the value of the chargeType property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *     
			 */
			public void setChargeType(String value) {
				this.chargeType = value;
			}

			/**
			 * Gets the value of the chargeAmount property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link BigDecimal }
			 *     
			 */
			public BigDecimal getChargeAmount() {
				return chargeAmount;
			}

			/**
			 * Sets the value of the chargeAmount property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link BigDecimal }
			 *     
			 */
			public void setChargeAmount(BigDecimal value) {
				this.chargeAmount = value;
			}

			/**
			 * Gets the value of the currency property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link String }
			 *     
			 */
			public String getCurrency() {
				return currency;
			}

			/**
			 * Sets the value of the currency property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *     
			 */
			public void setCurrency(String value) {
				this.currency = value;
			}

		}

	}

}
