//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.01 at 02:39:45 PM IST 
//


package com.tayyarah.api.hotel.travelguru.booking.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HotelReservation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotelReservation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoomStays" type="{http://www.opentravel.org/OTA/2003/05}RoomStays"/>
 *         &lt;element name="ResGuests" type="{http://www.opentravel.org/OTA/2003/05}ResGuests"/>
 *         &lt;element name="ResGlobalInfo" type="{http://www.opentravel.org/OTA/2003/05}ResGlobalInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelReservation", propOrder = {
    "roomStays",
    "resGuests",
    "resGlobalInfo"
})
public class HotelReservation
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "RoomStays", required = true)
    protected RoomStays roomStays;
    @XmlElement(name = "ResGuests", required = true)
    protected ResGuests resGuests;
    @XmlElement(name = "ResGlobalInfo", required = true)
    protected ResGlobalInfo resGlobalInfo;

    /**
     * Gets the value of the roomStays property.
     * 
     * @return
     *     possible object is
     *     {@link RoomStays }
     *     
     */
    public RoomStays getRoomStays() {
        return roomStays;
    }

    /**
     * Sets the value of the roomStays property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomStays }
     *     
     */
    public void setRoomStays(RoomStays value) {
        this.roomStays = value;
    }

    /**
     * Gets the value of the resGuests property.
     * 
     * @return
     *     possible object is
     *     {@link ResGuests }
     *     
     */
    public ResGuests getResGuests() {
        return resGuests;
    }

    /**
     * Sets the value of the resGuests property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResGuests }
     *     
     */
    public void setResGuests(ResGuests value) {
        this.resGuests = value;
    }

    /**
     * Gets the value of the resGlobalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ResGlobalInfo }
     *     
     */
    public ResGlobalInfo getResGlobalInfo() {
        return resGlobalInfo;
    }

    /**
     * Sets the value of the resGlobalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResGlobalInfo }
     *     
     */
    public void setResGlobalInfo(ResGlobalInfo value) {
        this.resGlobalInfo = value;
    }

}
